version: '3'

services:
  db_os1:
    image: mysql:5.7
    volumes:
      - db.0:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: chahat
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: dr_db

  drupalos:
    image: drupal:8-apache
    depends_on:
      - db_os1
    volumes:
      - drupal.modules:/var/www/html/modules
      - drupal.profiles:/var/wwww/html/profiles
      - drupal.themes:/var/www/html/themes
    restart: always
    ports:
      - 8888:80
volumes:
  drupal.modules:
  drupal.profiles:
  drupal.themes:
  db.1:
 
